import type { DocumentModel, Endpoint } from './types.js';
import { uniqueEndpoints } from './unique-endpoints.js';
import { DEFAULT_TAG } from './normalize.js';

export type SpecLintRule =
  | 'missing-summary'
  | 'missing-description'
  | 'missing-tags'
  | 'no-error-response'
  | 'missing-response-description'
  | 'duplicate-operation-id';

export interface SpecLintIssue {
  /** `undefined` for document-level issues (e.g. `duplicate-operation-id`), which aren't
   * anchored to one specific endpoint. */
  method: string | undefined;
  path: string | undefined;
  rule: SpecLintRule;
  message: string;
}

function lintEndpoint(endpoint: Endpoint): SpecLintIssue[] {
  const issues: SpecLintIssue[] = [];
  const base = { method: endpoint.method, path: endpoint.path };

  if (!endpoint.summary) {
    issues.push({ ...base, rule: 'missing-summary', message: 'no summary declared' });
  }
  if (!endpoint.description) {
    issues.push({ ...base, rule: 'missing-description', message: 'no description declared' });
  }
  // `normalizeDocument()` assigns `[DEFAULT_TAG]` to an operation with no `tags` declared at
  // all (see normalize.ts) — never an empty array — so that's the actual "untagged" signal.
  if (endpoint.tags.length === 0 || (endpoint.tags.length === 1 && endpoint.tags[0] === DEFAULT_TAG)) {
    issues.push({ ...base, rule: 'missing-tags', message: 'no tags declared (falls into the "Default" group)' });
  }
  if (!endpoint.responses.some((r) => /^[45]/.test(r.status))) {
    issues.push({ ...base, rule: 'no-error-response', message: 'no 4xx/5xx response declared' });
  }
  for (const response of endpoint.responses) {
    if (!response.description) {
      issues.push({
        ...base,
        rule: 'missing-response-description',
        message: `response ${response.status} has no description`,
      });
    }
  }

  return issues;
}

/**
 * Checks OpenAPI spec quality — not decorator/controller coverage (see `nestjs-docfy check`/
 * `lint`, which work from source `.docs.ts` files) but the final document itself: missing
 * summaries/descriptions, undocumented tags, endpoints with no error response declared,
 * responses with no description, and duplicate `operationId`s across the whole document.
 * Works against any OpenAPI 3.0/3.1 document, generated by this library or not — the
 * Redocly-CLI/Spectral-style "does this spec meet a quality bar" check `nestjs-docfy` didn't
 * have before: per-controller coverage says nothing about a spec assembled from a different
 * source, or about document-wide invariants like `operationId` uniqueness.
 */
export function lintSpec(document: DocumentModel): SpecLintIssue[] {
  const endpoints = uniqueEndpoints(document);
  const issues = endpoints.flatMap(lintEndpoint);

  const operationIdsSeen = new Map<string, Endpoint>();
  for (const endpoint of endpoints) {
    if (!endpoint.operationId) continue;
    const seenOn = operationIdsSeen.get(endpoint.operationId);
    if (seenOn) {
      issues.push({
        method: endpoint.method,
        path: endpoint.path,
        rule: 'duplicate-operation-id',
        message: `operationId "${endpoint.operationId}" is also used by ${seenOn.method} ${seenOn.path}`,
      });
    } else {
      operationIdsSeen.set(endpoint.operationId, endpoint);
    }
  }

  return issues;
}
